version: '3.7'
services:
  booksing:
    image: booksing
    environment:
      BOOKSING_TIMEZONE: America/New_York
    volumes:
      - ./data/books:/books
      - ./data/db:/db
      - ./data/failed:/failed
      - ./data/import:/import
    ports:
      - 7132:7132
    restart: always
